# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink: /:categories/:year/:month/:day/:title 
permalink: /blog/:year/:month/:title.html 
include: ['.htaccess']
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock"]
markdown: redcarpet
redcarpet:
  extensions:
    - footnotes
lsi: false
safe: false
highlighter: rouge
encoding: utf-8
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
paginate:         5
paginate_path: "/page/:num"
JB :
  ASSET_PATH : http://static.chenjun.com/assets
  IMAGE_PATH : http://static.chenjun.com/images
  STATIC_PATH : http://static.chenjun.com

# auto: true # deprecated

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
BASE_PATH: 
url: http://chenjun.com
title: 陈俊的网：浮生志
tagline: On The Way to Philistinism...
about: 陈俊［ChenJun(Zhu8)］的个人网站，江苏金坛人士，83年生人，电子产品、代码、海淘、智能设备、网页设计自虐狂，曼联死忠粉，王小波门下走狗。
author:
  name: Chen Jun(Zhu8)
  email: zhu8.net@gmail.com
  github: Zhu8
  twitter: 5CJ
  facebook: ichenjun
  googleplus: +ChenJun
  feedburner : Zhu8
  weibo : Zhu8
 # Custom vars
version:          2015.05.10